In [1]:
import numpy as np
import math
n = 3

In [2]:
def forward_elimination(A, b, n, pivot=False):
    """
    Calculates the forward part of Gaussian elimination.
    """
    for row in range(0, n-1):
        if pivot:
            if np.abs(A[row,row]) == 0:
                for k in range(i+1,n):
                    if np.abs(A[k,i])>np.abs(A[i,i]):
                        A[[i,k]]=A[[k,i]]             # Swaps ith and kth rows to each other
                        f[[i,k]]=f[[k,i]]
                        break
        
        for i in range(row+1, n):
            factor = np.round(A[i,row] / A[row,row], n)
            for j in range(row, n):
                A[i,j] = np.round(A[i,j] - factor * A[row,j], n)

            b[i] = np.round(b[i] - factor * b[row],n)

        print('A = \n%s and b = %s' % (A,b))
    return A, b

def back_substitution(a, b, n):
    """"
    Does back substitution, returns the Gauss result.
    """
    x = np.zeros((n,1))
    x[n-1] = np.round(b[n-1] / a[n-1, n-1], n)
    for row in range(n-2, -1, -1):
        sums = b[row]
        for j in range(row+1, n):
            sums = np.round(sums - a[row,j] * x[j],n)
        x[row] = np.round(sums / a[row,row],n)
    return x

def gauss(A, b, pivot=False):
    """
    This function performs Gauss elimination without pivoting.
    """
    n = A.shape[0]

    # Check for zero diagonal elements
    if any(np.diag(A)==0):
        raise ZeroDivisionError(('Division by zero will occur; '
                                  'pivoting currently not supported'))

    A, b = forward_elimination(A, b, n, pivot)
    return back_substitution(A, b, n)

In [7]:
A = np.array([[6 , 2, 2],
     [2, round(2/3, n), round(1/3, n)],
     [1, 2, -1]])
B = np.array([[-2],
    [1],
    [0]])
print(gauss(A,B))
print('\n')
print(gauss(A,B,pivot=True))

A = 
[[ 6.000e+00  2.000e+00  2.000e+00]
 [ 2.000e-03  1.000e-03 -3.330e-01]
 [-2.000e-03  1.666e+00 -1.334e+00]] and b = [[-2]
 [ 1]
 [ 0]]
A = 
[[ 6.00000e+00  2.00000e+00  2.00000e+00]
 [ 2.00000e-03  1.00000e-03 -3.33000e-01]
 [-2.00000e-03  0.00000e+00  5.53444e+02]] and b = [[   -2]
 [    1]
 [-1666]]
[[ 1.337]
 [-2.   ]
 [-3.01 ]]


A = 
[[ 6.00000e+00  2.00000e+00  2.00000e+00]
 [ 2.00000e-03  1.00000e-03 -3.33000e-01]
 [-2.00000e-03  0.00000e+00  5.53444e+02]] and b = [[   -2]
 [    1]
 [-1666]]
A = 
[[ 6.00000e+00  2.00000e+00  2.00000e+00]
 [ 2.00000e-03  1.00000e-03 -3.33000e-01]
 [-2.00000e-03  0.00000e+00  5.53444e+02]] and b = [[   -2]
 [    1]
 [-1666]]
[[ 1.337]
 [-2.   ]
 [-3.01 ]]
